### ISSUE TITLE
[Bug]: UI quirk in Transactions view

### ISSUE THREAD

**Issue by dmohns** [EnAccess/micropowermanager#443]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/EnAccess/micropowermanager/blob/main/CONTRIBUTING.md) for this project, if it exists.
- [x] I agree to follow the [Code of Conduct](https://github.com/EnAccess/micropowermanager/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/EnAccess/micropowermanager/issues) for a feature request that matches the one I want to file, without success.

### Expected Behavior

N/A

### Actual Behavior

Currently the Transactions view looks like this:

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/0ffb3e0a-6f59-4e7f-9ee5-972521f10492" />

Looks like some CSS from the navbar is affecting the list items, which shouldn't.

### Steps to reproduce

Open: https://demo.micropowermanager.io/#/transactions

### What operating system(s) are you using?

macOS

**Comment by javidmirzaei** [comment]
The issue seems to be caused by the `active` class applied to `<tr>` elements. This class might have global CSS styles affecting the transaction rows. 

Here are some suggestions to fix it:

1. **Remove the `active` class** from the `<tr>` elements if it's not required.
2. **Use a specific class** like `transaction-active` instead of `active` for styling these rows, and update your CSS accordingly.
3. **Override styles**: Ensure the table styles are applied correctly by using more specific selectors or `!important`.

Let me know if you need help with implementing any of these solutions
